Add a post-generate script to fix invalid constants
Nutanix has some enums that start with `$` which openapi-generator-cli
replaces with `_` which is an invalid first character for a ruby
constant.

This leads to the following type errors:
```
irb(main):002> NutanixVmm::VmmV40AhvConfigVlanMode.all_vars
/home/grare/adam/src/manageiq/nutanix_vmm-sdk-ruby/lib/nutanix_vmm/models/vmm_v40_ahv_config_vlan_mode.rb:24:in `all_vars': undefined local variable or method `_UNKNOWN' for class NutanixVmm::VmmV40AhvConfigVlanMode (NameError)

      @all_vars ||= [ACCESS, TRUNK, _UNKNOWN, _REDACTED].freeze
                                    ^^^^^^^^
```